version: '2'

services:

  node-jaguer:
    build: node-jaguer-madrid/.
    image: barreiro/node-jaguer
    command: yarn start
    ports:
      - "2525:80"
    volumes:
      - ./node-jaguer-madrid/src:/usr/src/jaguer/src
      - ./node-jaguer-madrid/public:/usr/src/jaguer/public

  angular_srv:
    build: ng-jaguer-madrid/.
    image: barreiro/angular
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./ng-jaguer-madrid/src:/usr/src/app/src
      - ./ng-jaguer-madrid/dist:/usr/src/app/dist
    command: ["ng", "build", "-prod", "--output-path=/usr/src/app/dist/build"]

  mongo_jaguer:
    image: mongo:3.2
    command: mongod --smallfiles
    expose:
      - "27017"
    ports:
      - "27017:27017"

  nginx_jaguer:
    build: nginx/.
    image: barreiro/nginx
    ports:
      - 80:80
    volumes:
      - ./ng-jaguer-madrid/dist:/usr/share/nginx/html

volumes:
  angularvol: {}